// place files you want to import through the `$lib` alias in this folder.
import Dashboard from "./organisms/dashboard.svelte";
import Button from "./atoms/button/button.svelte";
import Card from "./atoms/card/card.svelte";
import Dropdown from "./atoms/dropdown/dropdown.svelte";
import CardContainer from "./molecules/card-container/card-container.svelte";
import Product from "./organisms/product.svelte";
import Input from "./atoms/input/input.svelte";
import Header from "./organisms/dashboard.svelte";
import FilledStarIcon from "./icons/unfilled-star.svelte"
import UnfilledStarIcon from "./icons/unfilled-star.svelte"
import SearchIcon from "./icons/search.svelte";
import CartIcon from "./icons/cart.svelte";
import Category from "./atoms/category/category.svelte";
import RangeContainer from "./molecules/range-container";
import Range from "./atoms/range/range.svelte";
import ForwardIcon from "./icons/forward.svelte";
import BackwardIcon from "./icons/backward.svelte";
import Star from "./atoms/star/star.svelte" 
import CartCard from "./organisms/cart.svelte";
